### ISSUE TITLE
Add downloads block

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-blocks#1]
There's a number of block options that need to be built out.

Currently there's only the ones pictured here:

<img width="1668" alt="screen shot 2018-07-21 at 6 33 33 pm" src="https://user-images.githubusercontent.com/52581/43033075-9b0a8712-8d17-11e8-9e9a-41016821595c.png">

___

To do:

- [x] Number of downloads
- [x] Columns
- [x] Show Buy Button
- [x] Show Thumbnails
- [x] Show excerpt
- [x] Show full content
- [x] Show no excerpt or full content
- [x] Show downloads by category
- [x] Show downloads by order option
- [x] Show downloads by orderby option
- [x] Show Pagination

There are other options the `[downloads]` shortcode has (see below) that I'm not sure if we should bring over to the downloads block. I like the simplicity of the current set of options and adding too many UI options will clutter and confuse. Worst case scenario, you can just use the regular `[downloads]` shortcode in a shortcode block and have exactly what you want.

Things like:

- Manually selecting the downloads that should be shown in the download grid. In the shortcode, this is achieved using the `ids` attribute.

- Selecting more than one download category to show the downloads from. In the shortcode this is achieved with the `category` attribute.

- Selecting one or more download tags

- Excluding specific download categories

- Excluding specific download tags.

- Relation

- Author

**Comment by amdrew** [comment]
You can now show/hide thumbnails and set the order:

<img width="284" alt="screen shot 2018-07-23 at 10 43 38 pm" src="https://user-images.githubusercontent.com/52581/43072377-fbeef0d2-8ec9-11e8-865f-5be17182d882.png">

**Comment by amdrew** [comment]
Added an "Order By" select menu:

<img width="281" alt="screen shot 2018-07-23 at 11 05 05 pm" src="https://user-images.githubusercontent.com/52581/43073217-de220ffa-8ecc-11e8-9f39-171a10b752b6.png">

**Comment by amdrew** [comment]
Added `Show Excerpt` and `Show Full Content` toggles. Toggling one on while the other is already on will force the other off. Also allows both options to be toggled off so neither will show (like the shortcode).

<img width="291" alt="screen shot 2018-07-26 at 12 57 04 am" src="https://user-images.githubusercontent.com/52581/43202177-de0d4d88-906e-11e8-91f1-0356ef3b0879.png">

**Comment by amdrew** [comment]
👍 Thanks @davidsherlock!

**Comment by amdrew** [comment]
Current set of block options. Don't think we need much else for an initial version:

<img width="281" alt="screen shot 2018-07-28 at 2 54 42 pm" src="https://user-images.githubusercontent.com/52581/43352342-4012c54a-9276-11e8-8dd4-4611f2c184fa.png">

**Comment by spencerfinnell** [comment]
Cool! I think the Order select should be after Order By so you know what you’re changing the order of.

**Comment by amdrew** [comment]
I agree, good catch 👍

**Comment by amdrew** [comment]
The `Order` and `Order By` select menus are temporarily out of order. Switched to using the EDD API for fetching downloads though it doesn't look like we support `order` and `orderby` in the API.

**Comment by amdrew** [comment]
Submitted issue and PR: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6861

**Comment by amdrew** [comment]
Closing. Anything else can be added as separate issues.
