### ISSUE TITLE
Downloads do not show for multisite folder installations

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-blocks#11]
When using EDD Blocks with a multi-site folder installation (site.com/sitename), the downloads block cannot fetch the downloads.

**Comment by amdrew** [comment]
PR: https://github.com/easydigitaldownloads/edd-blocks/pull/12

@mintplugins When you get a chance, can you test this PR against your multisite folder installation? In my testing this fixes the issue we experienced whereby adding the block did not show any downloads.

**Comment by spencerfinnell** [comment]
@amdrew Gutenberg has https://github.com/WordPress/gutenberg/blob/master/lib/client-assets.php#L405-L408 which isn't finalized so using your own is the right move for now.

**Comment by mintplugins** [comment]
@amdrew that fixed it! 👍 🙌🤩🎉🎊👏

**Comment by amdrew** [comment]
Thanks @spencerfinnell. I'd imagine they'd add a little JS helper function in the near future to get the site URL.

@mintplugins 💯
