### ISSUE TITLE
Refactor taxonomy image support

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-blocks#21]
Currently it's possible to add an image against a taxonomy (e.g. download category):

<img width="795" alt="screen shot 2018-10-29 at 3 04 00 pm" src="https://user-images.githubusercontent.com/52581/47625749-e2fd7a80-db8b-11e8-9fa0-2588646ea506.png">

This is so we can output a grid of download categories with the relevant image:

<img width="838" alt="screen shot 2018-10-29 at 3 07 14 pm" src="https://user-images.githubusercontent.com/52581/47625821-5901e180-db8c-11e8-8df4-4519fd5f7ef7.png">

The code to do this (borrowed from elsewhere) is a bit janky. For example (and as shown in the screenshot) there's an "Add image" button when the image has already been added.

I recall discussing this with @JJJ at the company meetup and I believe he has a class we could borrow from one of his other plugins which would make this a lot tidier.

**Comment by JJJ** [comment]
https://github.com/stuttter/wp-term-images

There is a base UI class that does all the heavy lifting for hooking in to all the places, including the JS.

**Comment by amdrew** [comment]
Chur @JJJ !

**Comment by amdrew** [comment]
So far I've just added the required files (from JJJ's plugin) into EDD Blocks, tweaked the meta_key + the taxonomies it loads for, but so far so good! Feels much nicer.

<img width="821" alt="screen shot 2018-11-06 at 9 56 23 am" src="https://user-images.githubusercontent.com/52581/48026227-5580e280-e1aa-11e8-8200-ed9181c4933e.png">

**Comment by amdrew** [comment]
This is good enough for now, merged and closed.
