### ISSUE TITLE
PHP Notice:  Undefined index: className

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-blocks#38]
While testing with WordPress 5.0 RC3 I noticed this notice:

```
PHP Notice:  Undefined index: className in /wp-content/plugins/edd-blocks/includes/blocks/downloads/index.php on line 17
```

**Comment by amdrew** [comment]
@easydigitaldownloads/core-team  

PR: https://github.com/easydigitaldownloads/edd-blocks/pull/39

To replicate:

1. Add the Downloads block to the new WP editor
2. Change the `Display` select menu in the block's settings to `Download Categories`
3. Publish or update the page.
4. The error should be shown in your error logs. Alternatively visit the front-end page to trigger the error.

**Comment by SDavisMedia** [comment]
Replicated on `master` and confirmed fixed on `issue/38`. :+1:

**Comment by misulicus** [comment]
Replicated and fixed on `issue/38`
