### ISSUE TITLE
PHP Notice:  Undefined index: category

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-blocks#40]
```
PHP Notice:  Undefined index: category in /wp-content/plugins/edd-blocks/includes/blocks/downloads/index.php on line 46
```

To replicate:

1. Add the Downloads block to the new WP editor
1. Change the `Display` select menu in the block's settings to `Download Categories`
1. Publish or update the page.
1. Change the `Display` select menu in the block's settings back to `Downloads`
1. Update the page and the error should be shown in your error logs.

**Comment by amdrew** [comment]
@easydigitaldownloads/core-team PR: https://github.com/easydigitaldownloads/edd-blocks/pull/41

To test, confirm that downloads, categories and tags still work as intended with no errors.

**Comment by cklosowski** [comment]
@amdrew I'm still getting these errors on RC3, even on branch `issue/40`. I've deactivated all EDD extensions. I don't even have to do the steps above to reproduce. I just  need to click 'Add New' for creating a new post and I get it. The stack trace I'm seeing is:


```
the_block_editor_meta_boxes()
wp-admin/edit-form-blocks.php:405
the_block_editor_meta_box_post_form_hidden_fields()
wp-admin/includes/post.php:2066
do_action_deprecated()
wp-admin/includes/post.php:2205
_deprecated_hook()
wp-includes/plugin.php:629
wp-includes/functions.php:4112
```

**Comment by cklosowski** [comment]
Strike that I'm seeing a different error, saying:
```
edit_form_advanced is deprecated since version 5.0.0! Use block_editor_meta_box_hidden_fields instead. This action is still supported in the classic editor, but is deprecated in the block editor.
```

**Comment by cklosowski** [comment]
Ok got it replicated  on `master` and verified the fix on `issue/40`. :+1: from me.

**Comment by misulicus** [comment]
i keep getting this:
`[06-Dec-2018 19:32:09 UTC] PHP Notice:  Undefined index: className in D:\MAMP\htdocs\edd\wp-content\plugins\edd-blocks\includes\blocks\downloads\index.php on line 17`

**Comment by SDavisMedia** [comment]
@misulicus that's a separate issue addressed in #38

**Comment by misulicus** [comment]
Ok silly me..

**Comment by SDavisMedia** [comment]
Replicated on `master`. Confirmed fixed on `issue/40`. :+1:
