### ISSUE TITLE
Alignment (width) not being honoured on download terms block

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/edd-blocks#47]
If I set `align-wide` (or `align-full`) neither is being honoured by the block. The classes are never added and it seems they are not being set either.

It's worth noting that it would be useful to have a filter here as well, so it's possible to add custom classes if required.

For reference I am using the latest Themedd 1.1 build.

**Comment by amdrew** [comment]
Replicated 👍

Works on downloads, just not tags or categories.

**Comment by amdrew** [comment]
PR: https://github.com/easydigitaldownloads/edd-blocks/pull/48

@davidsherlock Can you test that? I have confirmed the classes are being added to tags and categories now.

**Comment by davidsherlock** [comment]
@amdrew, that fixes the issue but it would be useful to be able to filter the classes as well (if that can be added).

**Comment by davidsherlock** [comment]
I will open a seperate issue for that.
