### ISSUE TITLE
Update the "Tested up to" plugin header to remove banner on .org

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-blocks#55]
The `Tested up to` needs an update (after some testing of course) to remove the banner on the .org page:

https://wordpress.org/plugins/edd-blocks/

**Comment by cklosowski** [comment]
I'll verify the version works with latest 5.4 beta and update it. We don't need a full code push to do that.

**Comment by cklosowski** [comment]
Done:
![image](https://user-images.githubusercontent.com/1390124/74900131-143f2280-535c-11ea-818e-f0ced0f4b56a.png)
