### ISSUE TITLE
Use Standard Imports for WordPress Packages

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/edd-blocks#64]
Currently WordPress packages are referenced through the global `wp` object to avoid needing to explicitly add `@wordpress/*` packages as dependencies to the project. After #58 is completed with the Dependency Extraction plugin enabled we can reference the packages directly.

Before:

```js
const { select } = wp.data;
```

After:

```js
import { select } from '@wordpress/data';
```

The current implementation is what is ultimately generated, but the standard import style adds consistency for imports across the project. It will also ensure the Dependency Extraction plugin can find all `@wordpress/*` packages.

**Comment by LisaCee** [comment]
@spencerfinnell, should I remove `{ select }` from `edit.js`?  It is declared but never used.

**Comment by spencerfinnell** [comment]
@LisaCee Yes. Unused variables can be removed. They will be reported in the linter eventually.
