### ISSUE TITLE
Add title/subtitle support to download blocks

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/edd-blocks#9]
To keep styling coherent, it would be useful to be able to pass a `title` and `subtitle` into the downloads short-code/block. I actually built this and have it working on the `[downloads]` short-code, this allows you to easily build homepage layouts like this:

<img width="1152" alt="screenshot 2018-08-15 01 16 45" src="https://user-images.githubusercontent.com/22668877/44125159-e843fb66-a028-11e8-9dda-efa76d3157ad.png">

Here is another example:  https://demos.bigboxwc.com/deco/

This is beneficial for a few reasons, typically when you try to add this manually in WordPress it breaks the layout by adding orphan `<p>` and `<br>` tags, so if I add a header manually it usually requires custom styling to make it work out of the box, where if it was part of the block it would function more seamless and of course be optional to the user.

This might be worth adding at "block" level for both the categories and download shortcodes.

**Comment by davidsherlock** [comment]
Kind of mixed on that one, since it's schematically it feels part of the "block" in relation to the downloads.

**Comment by amdrew** [comment]
I agree with @spencerfinnell. Let's wait for Gutenberg's container block. Adding a new block for the heading/subtitle gives more flexibility.

Going by the airbnb example, their headings are a sibling of the grid (highlighted the heading below and in the source), and both the grid and heading are a child of the section (which would be the container/section block):

<img width="668" alt="screen shot 2018-10-29 at 2 51 43 pm" src="https://user-images.githubusercontent.com/52581/47625474-4686a880-db8a-11e8-89ca-e04771258160.png">
